apiVersion: v1
kind: Service
metadata:
  name: locnd-coworking
spec:
  type: LoadBalancer
  selector:
    service: locnd-coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locnd-coworking
  labels:
    service: locnd-coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locnd-coworking
  template:
    metadata:
      labels:
        service: locnd-coworking
    spec:
      containers:
      - name: locnd-coworking
        image: 463284152732.dkr.ecr.us-east-1.amazonaws.com/locnd-coworking-analytic:4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - configMapRef:
              name: locnd-postgresql-configmap
          - secretRef:
              name: locnd-postgresql-secrets
      restartPolicy: Always